// Usage: node scripts/embed-font.mjs  -> writes src/pdf/fonts/ptsans.ts
import { readFileSync, writeFileSync } from 'node:fs';
const ttf = readFileSync('src/pdf/fonts/PT_Sans-Web-Regular.ttf');
const b64 = ttf.toString('base64');
writeFileSync(
  'src/pdf/fonts/ptsans.ts',
  `// Generated by scripts/embed-font.mjs from PT_Sans-Web-Regular.ttf (SIL OFL 1.1, see OFL.txt). Do not edit.\nexport const PTSANS_REGULAR_BASE64 =\n  '${b64}';\n`,
);
console.log(`wrote src/pdf/fonts/ptsans.ts (${b64.length} chars)`);
